#!/usr/bin/perl -w

use IRCKB;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "IRCKB",
   ReceiveHandler => \&Receive);
$UNIVERSAL::irckb = IRCKB->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::irckb->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::irckb->Execute();
